spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID:YymH4a_h3ZNvKYkzTkCX}
            client-secret: ${NAVER_CLIENT_SECRET:UDiHWmw8sS}
            redirect-uri: ${BACKEND_URL:http://localhost:8080}/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image, nickname, mobile
            client-name: Naver

app:
  frontend-url: ${FRONTEND_URL:http://localhost}

naver:
  oauth:
    client-id: ${NAVER_CLIENT_ID:YymH4a_h3ZNvKYkzTkCX}
    client-secret: ${NAVER_CLIENT_SECRET:UDiHWmw8sS}
    auth-uri: https://nid.naver.com/oauth2.0/authorize
    redirect-uri: ${BACKEND_URL:http://localhost:8080}/api/auth/naver/callback
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
