spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wongoo3?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 15730254791!a

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: YymH4a_h3ZNvKYkzTkCX
            client-secret: UDiHWmw8sS
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image, nickname, mobile
            client-name: Naver

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

naver:
  oauth:
    client-id: YymH4a_h3ZNvKYkzTkCX
    client-secret: UDiHWmw8sS
    auth-uri: https://nid.naver.com/oauth2.0/authorize
    redirect-uri: http://localhost:8080/api/auth/naver/callback
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me
